# Generated by Django 2.0.6 on 2018-06-11 13:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EventoTrabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabalhos.Evento')),
                ('trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabalhos.Trabalho')),
            ],
        ),
        migrations.RemoveField(
            model_name='arquivo',
            name='nome',
        ),
        migrations.AddField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(default=django.utils.timezone.now, max_length=255, unique=True, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='trabalhos',
            field=models.ManyToManyField(through='trabalhos.EventoTrabalho', to='trabalhos.Trabalho'),
        ),
    ]
