# Generated by Django 2.0.6 on 2018-06-15 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0003_auto_20180612_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(max_length=255, unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='natureza',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='trabalho',
            unique_together={('ano', 'titulo', 'natureza', 'tag')},
        ),
    ]
