# Generated by Django 2.0.6 on 2018-06-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0004_auto_20180615_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='anoFim',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
