# Generated by Django 2.0.6 on 2018-06-17 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0008_auto_20180617_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabalho',
            name='tag',
        ),
        migrations.RenameField(
            model_name='trabalho',
            old_name='nova_tag',
            new_name='tag',
        ),
    ]
