# Generated by Django 2.0.6 on 2018-06-18 12:07

from django.db import migrations, models
import django.db.models.deletion
from trabalhos.models import Natureza


def migrarNaturezas(apps, schema_editor):
    trabalhos = apps.get_model('trabalhos', 'trabalho')
    naturezas = apps.get_model('trabalhos', 'natureza')
    for trabalho in trabalhos.objects.all().iterator():
        _naturezas = naturezas.objects.filter(nome=trabalho.natureza)
        if len(_naturezas) == 0:
            natureza = Natureza()
            natureza.nome = trabalho.natureza
            natureza.save()


def associarNaturezas(apps, schema_editor):
    trabalhos = apps.get_model('trabalhos', 'trabalho')
    naturezas = apps.get_model('trabalhos', 'natureza')
    for trabalho in trabalhos.objects.all().iterator():
        natureza = naturezas.objects.get(nome=trabalho.natureza)
        trabalho.nova_natureza = natureza
        trabalho.save()


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0010_auto_20180618_1207'),
    ]

    operations = [
        migrations.RunPython(migrarNaturezas),
        migrations.RunPython(associarNaturezas),
    ]   
