# Generated by Django 2.0.6 on 2018-06-25 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='ordem',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trabalhos.Tag'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='entidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trabalhos.Entidade'),
        ),
    ]
