# Generated by Django 2.0.6 on 2018-06-25 22:10

from django.db import migrations, models
import django.utils.timezone

def atualizar(objs):
    for obj in objs.objects.all().iterator():
        obj.descricao = obj.nome
        obj.save()

def atualizarEntidades(apps, schema_editor):
    atualizar(apps.get_model('trabalhos', 'entidade'))

def atualizarTags(apps, schema_editor):
    atualizar(apps.get_model('trabalhos', 'tag'))
    
def atualizarNaturezas(apps, schema_editor):
    atualizar(apps.get_model('trabalhos', 'natureza'))

class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0013_auto_20180625_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='descricao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(atualizarEntidades),
        migrations.AlterField(
            model_name='entidade',
            name='descricao',
            field=models.CharField(max_length=255, null=False),
        ),
        migrations.AddField(
            model_name='natureza',
            name='descricao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(atualizarNaturezas),
        migrations.AlterField(
            model_name='natureza',
            name='descricao',
            field=models.CharField(max_length=255, null=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='descricao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(atualizarTags),
        migrations.AlterField(
            model_name='tag',
            name='descricao',
            field=models.CharField(max_length=255, null=False),
        ),
    ]
